spring:
  datasource:
    password: password
    url: jdbc:mysql://localhost:3306/ApartmentFinder?serverTimezone=UTC&useSSL=false
    username: root
  jpa:
    hibernate:
      ddl-auto: none

  security:
    oauth2:
      client:
        registration:
         google:
          client-id: <client ID>
          client-secret: <Client secret>

          scope:
           - email
           - profile
